# Generated by Django 4.2.5 on 2023-10-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobilenumber',
            field=models.IntegerField(),
        ),
    ]
