# Generated by Django 4.2.5 on 2023-10-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0004_alter_userprofile_mobilenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
