# Generated by Django 4.2.5 on 2023-10-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0005_remove_userprofile_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
